In [ ]:
import requests
import pandas as pd
import os
import re
from tqdm import tqdm #barra de progreso
from dotenv import load_dotenv 

session = requests.Session()

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None) #para ver toda la tabla, en nuestro caso son solo 30 se supone que no tenemos que tener problema

API_KEY = '2c6d07b262d82febbd27cf5327a36d55' 

artistas = [
    "La Fuga",
    "Héroes del Silencio",
    "Billie Eilish",
    "Love of Lesbian",
    "Estopa",
    "Mägo de Oz",
    "Mr. Kilombo",
    "Rozalén",
    "Taburete",
    "Extremoduro",
    "La Plazuela",
    "Veintiuno",
    "Ojete Calor",
    "Rata Blanca",
    "Vetusta Morla",
    "Leiva",
    "Bad Bunny",
    "Enrique Bunbury",
    "Marea",
    "Joaquín Sabina",
    "Rosalía",
    "Queen",
    "The Lumineers",
    "Foo Fighters",
    "Muse",
    "Metallica",
    "Ginebras",
    "IZAL",
    "Kaiser Chiefs",
    "Residente"
]

artistas = [a.strip() for a in artistas]

def limpiar_bio(texto):
    """Elimina etiquetas HTML como <a href=...>Read more</a>"""
    return re.sub(r'<[^>]+>', '', texto).strip()

#Funcion para llamar a la API
def obtener_info_artista(nombre):
    url = "http://ws.audioscrobbler.com/2.0/"
    params = {
        "method": "artist.getinfo",
        "artist": nombre,
        "api_key": API_KEY,
        "format": "json",
        "autocorrect" : 1,  
        "lang": "es"
     }
    
    response = session.get(url, params=params, timeout=10)
    response.raise_for_status() #lanza excepción si hay error HTTP
    return response.json()

def procesar_artista(nombre):
    try:
        data = obtener_info_artista(nombre)
        artista = data["artist"]
        
        bio = limpiar_bio(artista["bio"]["content"])
        listeners = int(artista["stats"]["listeners"])
        playcount = int(artista["stats"]["playcount"])
        similares = [a["name"] for a in artista["similar"]["artist"]]
        
        return {
            "artista": nombre,
            "biografia": bio,
            "listeners": listeners,
            "playcount": playcount,
            "similares": ", ".join(similares)
        }
    
    except KeyError as e:
        print(f"[KeyError] '{nombre}': clave no encontrada {e}")  #except especifico que muestra qué clave faltó
        return None
    except session.RequestException as e:
        print(f"[RequestError] '{nombre}': {e}")
        return None

In [ ]:
resultados = []
bar = tqdm(artistas, desc="Iniciando...")
 
for artista in bar:
    bar.set_description(f"Procesando: {artista}")
    info = procesar_artista(artista)
    if info:
        resultados.append(info)
 
print(f"\n✅ {len(resultados)}/{len(artistas)} artistas obtenidos correctamente")

Procesando: Residente: 100%|██████████| 30/30 [00:05<00:00,  5.44it/s]

✅ 30/30 artistas obtenidos correctamente

In [68]:
procesar_artista('LA fuga')

{'artista': 'LA fuga',
 'biografia': 'La Fuga son Pedro (voz y guitarra), Nando (guitarra) y Edu (batería): un grupo de Reinosa (Cantabria) con más de 500 conciertos a sus espaldas en una decena de giras, 8 discos publicados hasta la fecha, y una historia de constancia y rock and roll. Una banda cuyo esfuerzo ha situado en lo más alto del panorama de la música estatal, y cuyo comienzo se remonta a hace casi 15 años.\n\nEn el verano de 1996, más que el sofocante calor del olvidado sur de Cantabria, es la rutina como desolador panorama lo que provoca que cuatro músicos confluyan sus inquietudes en La Fuga. Rulo (voz y guitarra), Iñaky (bajo), Edu (batería) y Fito (guitarra), que ya habían buscado anteriormente una vía de escape por separado en la música, empiezan juntos a dar conciertos con versiones de grupos de rock nacionales.\n\nReinosa, conocida por su lucha obrera y sus inviernos, a cual más combativo, forjó desde el principio el carácter especial de una banda curtida con el corazón y los instintos. Simplemente confiando en sí mismos, La Fuga, que por encima de todo sostenían la validez del directo en el rock, grabaron su primera maqueta “El Camino” (1997), como un pretexto para seguir presentándose ante el público. En el primer álbum se rescatarían cuatro temas de aquella primera maqueta y años después llegarían a ser seis por insistencia de sus seguidores. \n\nEl disco “Mira” (1998) grabado en los estudios Sonido XXI de Esparza de Galar y editado por FAK Records sería la verdadera grabación de debut. Incluía temas que alcanzaron la categoría de himnos como Primavera del 87, Por verte sonreír o Al pie del cañón. “Mira” supuso, además de la primera gira de presentación más allá de los límites de Cantabria, la llegada de un nuevo guitarrista, Nando, y el abandono temporal de Fito, que regresaría a finales de año a partir de un concierto benéfico recogido en la grabación “Un juguete por Navidad”. Un año después, a las puertas de su segundo trabajo discográfico, Iñaki dejaría el grupo por discrepancias con el resto.\n\nComo ni la ansiada compañía que apoyase su siguiente grabación ni el bajista adecuado llegaban, el grupo, sin abandonar ni la carretera, ni el local, ni su férrea opción de vivir por y para la música, toma en pocos meses una doble decisión que marcaría su carrera: ajustarse como cuarteto pasando Rulo a ocuparse del bajo, y autoproducirse su segundo disco “A golpes de rock and roll” (2000).\n\nSi el marco característico de La Fuga eran en ese momento sus letras, una nutrida colección amores, desencuentros y noches compartidas, como P’aquí p’allá, Hasta nunca, Pedazo de morón o Los de siempre, la auténtica marca distintiva empieza a ser un estallido de directo potente, siempre en comunión con el público. Ese sonido y esa complicidad animarían a Javi y Juanan San Martín –propietarios de Sonido XXI donde el grupo había grabado todo su material– a apostar por La Fuga para su sello discográfico, EDG Music, con quien sacarían su siguiente disco.\n\n“A las doce” (2001) consolidaría la madurez de la  banda, brindaría varias melodías donde toda su generación y las posteriores pudieran vociferar sus desvelos y poner banda sonora a sus noches (Pa volar, Conversación habitación, Majareta, una nueva versión de P’aquí p’allá) y subiría a los de Reinosa a los escenarios más importantes del país. No conseguirlo hubiera sido injusto para quienes, desde arriba y desde abajo de las tablas de una escena del llamado rock estatal que a finales de los 90 parecía agotada, confiaban en escuchar algo nuevo.\n\nAl finalizar la gira de “A las doce”, DRO East West había olido el rastro de éxito que habían dejado los cántabros y tenían ganas de completar la embestida de rock en español que lanzaban desde su sello tras los recientes fichajes de otros grupos estandarte del panorama estatal; el ariete definitivo sería La Fuga con su nuevo álbum, “Calles de papel” (2003). La tempestuosa voz de Rulo en el escenario, el dominio de Nando de la guitarra, la presencia de Fito y la solidez rítmica de Edu, habían ensamblado una maquinaria casi perfecta que engrasada con el sudor del trabajo recorrería la península y las islas en una gira de presentación con más de 80 conciertos en los que convertían el rock and roll en un arte engañosamente sencillo ajeno a las modas musicales pasajeras. El objetivo no era sorprender a sus seguidores, sino conectar con ellos, y La Fuga lo conseguía.\n\nDespués de la gira más extensa del grupo hasta la fecha, llegaría el quinto trabajo de estudio. “Negociando gasolina” (2005), fue el disco con el que las cifras de venta confirmaron el estatus de La Fuga en primera línea del rock estatal. La buena acogida y la intensa gira sentaron las bases de una particular relación con el gran público, fuera incluso de los festivales y medios especializados. Buscando en la basura, Amor de contenedor o Heroína (versión de Los Calis) se convertirían a partir de entonces en temas imprescindibles en el repertorio. Todo el trabajo había valido la pena; los cuatro destilaban la ejecución exacta de sus roles, y su combinación escénica generaba una energía casi imbatible.\n\nLos 10 años de la banda se celebraron con un doble regalo para los seguidores del grupo, ideado inicialmente en conjunto pero editado por separado: “En directo” (2006), un disco grabado en la sala Aqualung (Madrid) para quienes venían reclamando una grabación acompañada de público que evidenciase con toda su fuerza el escenario como entorno natural de La Fuga; y “Nubes y claros” (2006), un experimento acústico, un proyecto intimista, poco convencional y melódico, que presentaron en una pequeña gira por teatros. Ambos discos definieron las dos caras de la carrera de una propuesta que convencía y emocionaba con la misma facilidad. Cerrarían el año 2007 con la primera gira por Latinoamérica, visitando Argentina, Uruguay y Chile.\n\nTras casi tres años sin presentar material inédito, “Asuntos pendientes” (2008) salda la deuda contraída con quienes esperaban nuevos temas de los reinosanos. En la misma línea que sus anteriores trabajos, el desamor y el amor de Jaleo y Los molinos, la melancolía de No sólo respirar y Malos pensamientos, o la denuncia social (desde el otro lado del charco en el caso de Villa Miseria) vuelven a centrar 11 nuevas canciones que serían la excusa para girar durante varios meses por España y Sudamérica.\n\nEn octubre de 2009 se anuncia el abandono de Rulo –que emprende su carrera en solitario– y la intención del resto de la banda de continuar adelante. Tras un invierno de búsqueda y trabajo, en el que Fito decidió desvincularse temporalmente de la música, en 2010 La Fuga presenta a Pedro (ex-Mr. Fylyn) como nuevo vocalista. Una gira de dos meses en septiembre y octubre presentará la nueva formación y dará paso a la grabación de un disco que verá la luz a principios de 2011 y del que ya puede escucharse Opciones como adelanto.\n\n\nDiscografía\n\n    * Mira (1998)\n    * A golpes de Rock and Roll (2000)\n    * A las doce (2001)\n    * Calles de papel (2003)\n    * Negociando gasolina (2005)\n    * La Fuga en directo (Sala Aqualung de Madrid) (2006)\n    * Nubes y claros (Acústico) (2006)\n    * Asuntos pendientes (2008)\n\nMaquetas\n\n    * El camino (1997)\n    * Un juguete por navidad (Edición limitada) (1999)\n\nhttp://www.lafuga.net/ Read more on Last.fm. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.',
 'listeners': 82583,
 'playcount': 2800945,
 'similares': 'Marea, Platero y tú, Rosendo, Los De Marras, Fito Y Fitipaldis'}

In [62]:
#Crear DataFrame
df_lastfm = pd.DataFrame(resultados)
df_lastfm.head() #con esto veo 5

,artista,biografia,listeners,playcount,similares
0,La Fuga,"La Fuga son Pedro (voz y guitarra), Nando (gui...",82583,2800945,"Marea, Platero y tú, Rosendo, Los De Marras, F..."
1,Héroes del Silencio,Héroes es el grupo de rock español de mayor éx...,202357,6110374,"Enrique Bunbury, Caifanes, Jaguares, Fobia, Ra..."
2,Billie Eilish,Billie Eilish Pirate Baird O'Connell​ (Los Áng...,4230582,836351191,"FINNEAS, Olivia Rodrigo, Melanie Martinez, Lan..."
3,Love of Lesbian,Love of Lesbian es un grupo de pop independien...,176513,11440267,"Lori Meyers, Viva Suecia, Izal, Vetusta Morla,..."
4,Estopa,Estopa es un grupo de pop/rumba/flamenco funda...,309127,8958630,"Melendi, El Canto del Loco, Extremoduro, Perez..."

In [63]:
df_lastfm #con esto sale toda la tabla

,artista,biografia,listeners,playcount,similares
0,La Fuga,"La Fuga son Pedro (voz y guitarra), Nando (gui...",82583,2800945,"Marea, Platero y tú, Rosendo, Los De Marras, F..."
1,Héroes del Silencio,Héroes es el grupo de rock español de mayor éx...,202357,6110374,"Enrique Bunbury, Caifanes, Jaguares, Fobia, Ra..."
2,Billie Eilish,Billie Eilish Pirate Baird O'Connell​ (Los Áng...,4230582,836351191,"FINNEAS, Olivia Rodrigo, Melanie Martinez, Lan..."
3,Love of Lesbian,Love of Lesbian es un grupo de pop independien...,176513,11440267,"Lori Meyers, Viva Suecia, Izal, Vetusta Morla,..."
4,Estopa,Estopa es un grupo de pop/rumba/flamenco funda...,309127,8958630,"Melendi, El Canto del Loco, Extremoduro, Perez..."
5,Mägo de Oz,"Mägo de Oz es un grupo proveniente de Madrid, ...",298682,13967733,"Warcry, Saratoga, Saurom, Tierra Santa, Rata B..."
6,Mr. Kilombo,Mr.Kilombo es una banda mestiza nacida en Madr...,18654,219292,"Pedro Pastor, TéCanela, El Niño de La Hipoteca..."
7,Rozalén,"Desde los 7 años, María Rozalén formó parte de...",50813,808513,"Vanesa Martín, Amaral, Despistaos, Valeria Cas..."
8,Taburete,Taburete es un grupo de música madrileño forma...,38467,699817,"Maldita Nerea, Siloé, Despistaos, Antonio Oroz..."
9,Extremoduro,"En 1987 Robe, cantante y guitarra, forma Extre...",181621,12244527,"Marea, Platero y tú, Fito Y Fitipaldis, La Fug..."
10,La Plazuela,La Plazuela es un grupo granadino formado por ...,14790,413329,"Califato ¾, Los Delinqüentes, María José Llerg..."
11,Veintiuno,VEINTIUNO es una joven banda de Toledo que def...,21487,593279,"Siloé, Sidonie, Lori Meyers, Miss Caffeina, Sa..."
12,Ojete Calor,"Ojete Calor son un grupo musical, formado por ...",21998,411650,"Ginebras, Siloé, Rozalén, Rigoberta Bandini, L..."
13,Rata Blanca,Rata Blanca es una banda argentina de metal qu...,199839,3903971,"Mägo de Oz, Ángeles del Infierno, Tierra Santa..."
14,Vetusta Morla,Vetusta Morla es una banda de rock alternativo...,165033,9816418,"Izal, Supersubmarina, Love of Lesbian, Viva Su..."
15,Leiva,"José Miguel Conejo Torres (Madrid, 30 de abril...",90371,2526073,"Pereza, Arde Bogotá, Sidecars, Vetusta Morla, ..."
16,Bad Bunny,"Benito Antonio Martínez Ocasio, mejor conocido...",2582126,407024693,"JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Vega..."
17,Enrique Bunbury,"Enrique Ortiz de Landázuri Yzarduy, mejor cono...",149785,4886184,"Héroes del Silencio, Jaguares, Fobia, Elefante..."
18,Marea,"Hacia el invierno de 1997, después de haber fo...",123625,5123402,"La Fuga, Extremoduro, Platero y tú, Fito Y Fit..."
19,Joaquín Sabina,Joaquín Ramón Martínez Sabina nació en Úbeda (...,237562,7708267,"Joan Manuel Serrat, Luis Eduardo Aute, Ismael ..."
20,Rosalía,"Rosalía Vila Tobella, conocida mundialmente co...",1867349,203697085,"Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO"
21,Queen,Queen es una banda de rock clásico creada en L...,7229689,426351148,"Freddie Mercury, Roger Taylor, Brian May, Fred..."
22,The Lumineers,"Es una banda de Denver Colorado (EE.UU.) , est...",2581910,92131692,"Caamp, The Head and the Heart, Vance Joy, Mt. ..."
23,Foo Fighters,Foo Fighters es una banda de rock alternativo ...,6375398,364121042,"Pearl Jam, Taylor Hawkins & The Coattail Rider..."
24,Muse,Muse es una banda de rock alternativo originar...,6397894,571485208,"Royal Blood, Placebo, Nothing But Thieves, Rad..."
25,Metallica,Metallica es una banda originaria de Estados U...,5185293,535774615,"Megadeth, Slayer, Pantera, Anthrax, Iron Maiden"
26,Ginebras,Ginebras es una banda que han formado entre 20...,22168,690618,"Cariño, Karavana, Shego, Niña Polaca, Carolina..."
27,IZAL,"IZAL es un grupo indie/pop de España, formado ...",66750,3071775,"Viva Suecia, Vetusta Morla, Supersubmarina, Ar..."
28,Kaiser Chiefs,Kaiser Chiefs son una banda británica de Leeds...,2882998,70455540,"Kasabian, Razorlight, Hard-Fi, The Fratellis, ..."
29,Residente,René Pérez Joglar (también conocido por su apo...,185421,2689421,"Calle 13, Ana Tijoux, Los Rivera Destino, Vico..."

In [64]:
#para verlos en orden de más popular a menos 
df_lastfm.sort_values(by="listeners", ascending=False)

,artista,biografia,listeners,playcount,similares
21,Queen,Queen es una banda de rock clásico creada en L...,7229689,426351148,"Freddie Mercury, Roger Taylor, Brian May, Fred..."
24,Muse,Muse es una banda de rock alternativo originar...,6397894,571485208,"Royal Blood, Placebo, Nothing But Thieves, Rad..."
23,Foo Fighters,Foo Fighters es una banda de rock alternativo ...,6375398,364121042,"Pearl Jam, Taylor Hawkins & The Coattail Rider..."
25,Metallica,Metallica es una banda originaria de Estados U...,5185293,535774615,"Megadeth, Slayer, Pantera, Anthrax, Iron Maiden"
2,Billie Eilish,Billie Eilish Pirate Baird O'Connell​ (Los Áng...,4230582,836351191,"FINNEAS, Olivia Rodrigo, Melanie Martinez, Lan..."
28,Kaiser Chiefs,Kaiser Chiefs son una banda británica de Leeds...,2882998,70455540,"Kasabian, Razorlight, Hard-Fi, The Fratellis, ..."
16,Bad Bunny,"Benito Antonio Martínez Ocasio, mejor conocido...",2582126,407024693,"JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Vega..."
22,The Lumineers,"Es una banda de Denver Colorado (EE.UU.) , est...",2581910,92131692,"Caamp, The Head and the Heart, Vance Joy, Mt. ..."
20,Rosalía,"Rosalía Vila Tobella, conocida mundialmente co...",1867349,203697085,"Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO"
4,Estopa,Estopa es un grupo de pop/rumba/flamenco funda...,309127,8958630,"Melendi, El Canto del Loco, Extremoduro, Perez..."
5,Mägo de Oz,"Mägo de Oz es un grupo proveniente de Madrid, ...",298682,13967733,"Warcry, Saratoga, Saurom, Tierra Santa, Rata B..."
19,Joaquín Sabina,Joaquín Ramón Martínez Sabina nació en Úbeda (...,237562,7708267,"Joan Manuel Serrat, Luis Eduardo Aute, Ismael ..."
1,Héroes del Silencio,Héroes es el grupo de rock español de mayor éx...,202357,6110374,"Enrique Bunbury, Caifanes, Jaguares, Fobia, Ra..."
13,Rata Blanca,Rata Blanca es una banda argentina de metal qu...,199839,3903971,"Mägo de Oz, Ángeles del Infierno, Tierra Santa..."
29,Residente,René Pérez Joglar (también conocido por su apo...,185421,2689421,"Calle 13, Ana Tijoux, Los Rivera Destino, Vico..."
9,Extremoduro,"En 1987 Robe, cantante y guitarra, forma Extre...",181621,12244527,"Marea, Platero y tú, Fito Y Fitipaldis, La Fug..."
3,Love of Lesbian,Love of Lesbian es un grupo de pop independien...,176513,11440267,"Lori Meyers, Viva Suecia, Izal, Vetusta Morla,..."
14,Vetusta Morla,Vetusta Morla es una banda de rock alternativo...,165033,9816418,"Izal, Supersubmarina, Love of Lesbian, Viva Su..."
17,Enrique Bunbury,"Enrique Ortiz de Landázuri Yzarduy, mejor cono...",149785,4886184,"Héroes del Silencio, Jaguares, Fobia, Elefante..."
18,Marea,"Hacia el invierno de 1997, después de haber fo...",123625,5123402,"La Fuga, Extremoduro, Platero y tú, Fito Y Fit..."
15,Leiva,"José Miguel Conejo Torres (Madrid, 30 de abril...",90371,2526073,"Pereza, Arde Bogotá, Sidecars, Vetusta Morla, ..."
0,La Fuga,"La Fuga son Pedro (voz y guitarra), Nando (gui...",82583,2800945,"Marea, Platero y tú, Rosendo, Los De Marras, F..."
27,IZAL,"IZAL es un grupo indie/pop de España, formado ...",66750,3071775,"Viva Suecia, Vetusta Morla, Supersubmarina, Ar..."
7,Rozalén,"Desde los 7 años, María Rozalén formó parte de...",50813,808513,"Vanesa Martín, Amaral, Despistaos, Valeria Cas..."
8,Taburete,Taburete es un grupo de música madrileño forma...,38467,699817,"Maldita Nerea, Siloé, Despistaos, Antonio Oroz..."
26,Ginebras,Ginebras es una banda que han formado entre 20...,22168,690618,"Cariño, Karavana, Shego, Niña Polaca, Carolina..."
12,Ojete Calor,"Ojete Calor son un grupo musical, formado por ...",21998,411650,"Ginebras, Siloé, Rozalén, Rigoberta Bandini, L..."
11,Veintiuno,VEINTIUNO es una joven banda de Toledo que def...,21487,593279,"Siloé, Sidonie, Lori Meyers, Miss Caffeina, Sa..."
6,Mr. Kilombo,Mr.Kilombo es una banda mestiza nacida en Madr...,18654,219292,"Pedro Pastor, TéCanela, El Niño de La Hipoteca..."
10,La Plazuela,La Plazuela es un grupo granadino formado por ...,14790,413329,"Califato ¾, Los Delinqüentes, María José Llerg..."

In [65]:
# ── MEJORA: exportar a CSV para no tener que volver a llamar a la API ──
df_lastfm.to_csv("lastfm_artistas.csv", index=False, encoding="utf-8-sig")
print("✅ Datos guardados en lastfm_artistas.csv")

✅ Datos guardados en lastfm_artistas.csv

In [66]:
#merge con Deezer (cuando tengas df_deezer disponible)
df_final = df_deezer.merge(df_lastfm, on="artista", how="left")
df_final.head()

NameError: name 'df_deezer' is not defined