In [86]:
import requests
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None) #para ver toda la tabla, en nuestro caso son solo 30 se supone que no tenemos que tener problema

In [87]:
API_KEY = '2c6d07b262d82febbd27cf5327a36d55'

In [97]:
artistas = [
    "La Fuga",
    "Héroes del Silencio",
    "Billie Eilish",
    "Love of Lesbian",
    "Estopa",
    "Mägo de Oz",
    "Mr. Kilombo",
    "Rozalén",
    "Taburete",
    "Extremoduro",
    "La Plazuela",
    "Veintiuno",
    "Ojete Calor",
    "Rata Blanca",
    "Vetusta Morla",
    "Leiva",
    "Bad Bunny",
    "Enrique Bunbury",
    "Marea",
    "Joaquín Sabina",
    "Rosalía",
    "Queen",
    "The Lumineers",
    "Foo Fighters",
    "Muse",
    "Metallica",
    "Ginebras",
    "IZAL",
    "Kaiser Chiefs",
    "Residente"
]
artistas = [a.strip() for a in artistas]

In [98]:
#Funcion para llamar a la API
def obtener_info_artista(nombre):
    url = "http://ws.audioscrobbler.com/2.0/"
    
    params = {
        "method": "artist.getinfo",
        "artist": nombre,
        "api_key": API_KEY,
        "format": "json"
    }
    
    response = requests.get(url, params=params)
    return response.json()

In [99]:
#funcion para limpiar datos
def procesar_artista(nombre):
    data = obtener_info_artista(nombre)
    
    try:
        artista = data["artist"]
        
        bio = artista["bio"]["summary"]
        listeners = int(artista["stats"]["listeners"])
        playcount = artista["stats"]["playcount"]
        
        similares = [a["name"] for a in artista["similar"]["artist"]]
        
        return {
            "artista": nombre,
            "biografia": bio,
            "listeners": listeners,
            "playcount": playcount,
            "similares": ", ".join(similares)
        }
    
    except:
        return None

In [ ]:
#Bucle para todos los artistas 
resultados = []

for artista in artistas:
    info = procesar_artista(artista)
    if info:
        resultados.append(info)

In [101]:
procesar_artista('Rozalén')

{'artista': 'Rozalén',
 'biografia': 'María de los Ángeles Rozalén Ortuño known as Rozalén (Albacete, June 12, 1986) is a Spanish singer-songwriter and guitarist.  <a href="https://www.last.fm/music/+noredirect/Rozal%C3%A9n">Read more on Last.fm</a>',
 'listeners': 50813,
 'playcount': '808513',
 'similares': 'Vanesa Martín, Amaral, Despistaos, Valeria Castro, Ana Belén'}

In [102]:
resultados

[{'artista': 'La Fuga',
  'biografia': 'Spanish rock band La Fuga were born in July of 1996 in Reinosa, a small industrial town south of Cantabria. Edu (drums), Rulo (guitar and voice), Fito (lead guitar and voice), and Inaki (bass) all left previous bands behind in hopes of forming a solid group. It was not long before La Fuga were performing regularly in Reinosa and the surrounding area. In June of 1997 the group took to the studio to record its first record, the self-produced El Camino. <a href="https://www.last.fm/music/La+Fuga">Read more on Last.fm</a>',
  'listeners': 82570,
  'playcount': '2800704',
  'similares': 'Marea, Platero y tú, Rosendo, Los De Marras, Fito Y Fitipaldis'},
 {'artista': 'Héroes del Silencio',
  'biografia': 'Héroes del Silencio (sometimes referred to as just Héroes) was a Spanish rock band from Zaragoza, Aragon, Spain formed by Juan Valdivia in 1987. In the 1990s they experienced success around Spain and the Americas, and various European countries including Germany, Belgium, Switzerland, France and Portugal becoming a successful Spanish group and icons in the history of the Rock en Español scene. After ten years and numerous albums, the band broke up in 1997. <a href="https://www.last.fm/music/+noredirect/H%C3%A9roes+del+Silencio">Read more on Last.fm</a>',
  'listeners': 202353,
  'playcount': '6110116',
  'similares': 'Enrique Bunbury, Caifanes, Jaguares, Fobia, Rata Blanca'},
 {'artista': 'Billie Eilish',
  'biografia': 'Billie Eilish Pirate Baird O\'Connell (born December 18th, 2001, in Los Angeles, California, USA) is an American singer-songwriter. She is recognised for her distinctive, alternative pop musical style and vocal delivery, and has become a prominent figure in 2020s popular culture. Eilish first gained public attention in 2015 with her debut single "Ocean Eyes", which was released on SoundCloud and written and produced by her brother Finneas O\'Connell. <a href="https://www.last.fm/music/Billie+Eilish">Read more on Last.fm</a>',
  'listeners': 4230582,
  'playcount': '836351191',
  'similares': 'FINNEAS, Olivia Rodrigo, Melanie Martinez, Lana Del Rey, Ariana Grande'},
 {'artista': 'Love of Lesbian',
  'biografia': 'Love of Lesbian is a Spanish indie pop/indie rock band. \nIn the beginning they were influenced by The Cure (they toured with them in Spain), Radiohead and R.E.M. Today they have the personal Love of Lesbian sound and style. There is always a "sold out" at all their concerts. Each one is a mix of party-concert-celebration-catharsis.\nSanti Balmes, the writer, main composer, and charismatic leader brings to each album excellent lyrics of high composition, from a delicious sense of humour to deep emotional tales. <a href="https://www.last.fm/music/Love+of+Lesbian">Read more on Last.fm</a>',
  'listeners': 176513,
  'playcount': '11440267',
  'similares': 'Lori Meyers, Viva Suecia, Izal, Vetusta Morla, Supersubmarina'},
 {'artista': 'Estopa',
  'biografia': 'Estopa is a pop/flamenco duo founded in 1999 by brothers José and David Muñoz of Cornellà de Llobregat (Baix Llobregat), Catalonia. Their first album, Estopa, has sold well over 1,000,000 copies to date (the equivalent of an American platinum album) and their latest, Voces de Ultrarumba, sold more than 200,000 copies on its first day of release. Their playful, Rumba-tinged compositions have made them one of the most successful pop groups in Spanish history, in terms of both album sales and critical acclaim. <a href="https://www.last.fm/music/Estopa">Read more on Last.fm</a>',
  'listeners': 309127,
  'playcount': '8958630',
  'similares': 'Melendi, El Canto del Loco, Extremoduro, Pereza, Los Delinqüentes'},
 {'artista': 'Mägo de Oz',
  'biografia': 'Mägo de Oz (Spanish for Wizard of Oz, with a metal umlaut) is a Spanish folk metal band from Begoña, Madrid, formed in 1988 by drummer Txus di Fellatio. The group became known for incorporating Celtic influences into its music, including the regular use of instruments such as violin and flute. According to founding member Txus di Fellatio, the band’s name was chosen to reflect the idea that life is a yellow brick road on which people travel together while pursuing their dreams. <a href="https://www.last.fm/music/+noredirect/M%C3%A4go+de+Oz">Read more on Last.fm</a>',
  'listeners': 298682,
  'playcount': '13967733',
  'similares': 'Warcry, Saratoga, Saurom, Tierra Santa, Rata Blanca'},
 {'artista': 'Mr. Kilombo',
  'biografia': 'Mr.Kilombo es una banda mestiza nacida en Madrid. Un cóctel musical en el que la rumba hace de hilo conductor y la timba, la samba, el reggae, el ska y el rock son algunos de los condimentos que se mezclan con elegancia para lograr un clima lisérgico que invita a la algarabía y la farra. Las letras, ácidas y directas a veces, sutiles y encriptadas otras, son responsabilidad de Miki Ramírez, que a su corta edad se ha convertido en todo un veterano de la composición urbana. <a href="https://www.last.fm/music/Mr.+Kilombo">Read more on Last.fm</a>',
  'listeners': 18654,
  'playcount': '219292',
  'similares': 'Pedro Pastor, TéCanela, El Niño de La Hipoteca, Antílopez, Sebastián Cortés'},
 {'artista': 'Rozalén',
  'biografia': 'María de los Ángeles Rozalén Ortuño known as Rozalén (Albacete, June 12, 1986) is a Spanish singer-songwriter and guitarist.  <a href="https://www.last.fm/music/+noredirect/Rozal%C3%A9n">Read more on Last.fm</a>',
  'listeners': 50813,
  'playcount': '808513',
  'similares': 'Vanesa Martín, Amaral, Despistaos, Valeria Castro, Ana Belén'},
 {'artista': 'Taburete',
  'biografia': ' <a href="https://www.last.fm/music/taburete">Read more on Last.fm</a>',
  'listeners': 38467,
  'playcount': '699817',
  'similares': 'Maldita Nerea, Siloé, Despistaos, Antonio Orozco, Sidecars'},
 {'artista': 'Extremoduro',
  'biografia': 'Extremoduro is a Spanish rock band from Plasencia, Extremadura. The band is led by Roberto Iniesta, also known as "Robe", or even "El rey de Extremadura" (the king of Extremadura).\n\nThe band was created in 1987 and is regarded as one of the most influential bands of the Spanish hard rock scene, besides being a complete symbol for their region. Iniesta\'s lyrics are often described as rude street poetry, with frequent allusions to drugs, love and self-destruction. <a href="https://www.last.fm/music/Extremoduro">Read more on Last.fm</a>',
  'listeners': 181621,
  'playcount': '12244527',
  'similares': 'Marea, Platero y tú, Fito Y Fitipaldis, La Fuga, Estopa'},
 {'artista': 'La Plazuela',
  'biografia': 'La Plazuela is a band from Granada (Spain) formed by Manuel Hidalgo "El Indio" and Luis Abril "El Nitro". This band rescues the purest ofits Andalusian roots and expands towards new electronic and digital sounds. They began in 2019 with their first EP "yunque,clavos y arcayatas" and they approach the more electronic sound in their latest single "Tangos de Copera" which has led them to sign with the Universal Music Spain label. In this editorial we mix these two worlds, the tradition of flamenco and the industrial electronics. <a href="https://www.last.fm/music/La+Plazuela">Read more on Last.fm</a>',
  'listeners': 14790,
  'playcount': '413329',
  'similares': 'Califato ¾, Los Delinqüentes, María José Llergo, Sanguijuelas del Guadiana, Camarón de la Isla'},
 {'artista': 'Veintiuno',
  'biografia': 'Veintiuno is a Spanish indie rock band from Toledo, Spain, formed in 2011. Their sound is a mix of alternative rock, indie pop, and soul, and they\'ve become known for their energetic live shows and introspective lyrics.\n\nThe band\'s current members are Diego Arroyo (vocals, guitar, and keyboards), Yago Banet (bass), Pepe Narváez (drums), and Rafa Pachón (guitar).\n\nVeintiuno self-released their first album, Nada parecido, in 2015, which was funded through a crowdfunding campaign. <a href="https://www.last.fm/music/Veintiuno">Read more on Last.fm</a>',
  'listeners': 21487,
  'playcount': '593279',
  'similares': 'Siloé, Sidonie, Lori Meyers, Miss Caffeina, Samuraï'},
 {'artista': 'Ojete Calor',
  'biografia': 'Ojete Calor is a electropop (or \'subnopop\' as they define themselves) duo comprised of  Aníbal Gómez and comedian and actor Carlos Areces. <a href="https://www.last.fm/music/Ojete+Calor">Read more on Last.fm</a>',
  'listeners': 21998,
  'playcount': '411650',
  'similares': 'Ginebras, Siloé, Rozalén, Rigoberta Bandini, Las Bistecs'},
 {'artista': 'Rata Blanca',
  'biografia': 'Rata Blanca was founded in 1985 by Walter Giardino after he left V8. Rata Blanca played together for about two years before their debut on August 15, 1987 in the theater "Luz y Fuerza" in Buenos Aires, Argentina. They later took part in the "Halley en Obras", along with other bands: Alakrán ("Skorpion"), JAF and Kamikaze, in 1988. That year they made their debut album with two hits: "Chico Callejero" ("Street Boy") and "El Sueño de la Gitana" ("Gypsy Woman\'s Dream"). <a href="https://www.last.fm/music/Rata+Blanca">Read more on Last.fm</a>',
  'listeners': 199839,
  'playcount': '3903971',
  'similares': 'Mägo de Oz, Ángeles del Infierno, Tierra Santa, Saratoga, Warcry'},
 {'artista': 'Vetusta Morla',
  'biografia': 'Vetusta Morla is a Spanish indie rock band originally from Tres Cantos, Madrid, who sings in Spanish. After nine years of musical journey, in February 2008 they published their first feature, Un día en el mundo. Three years later, in 2011, they published their second album, Maps. On April 8 after several years of touring Spain and other countries, they published their third album,La Deriva. In 2017 they publish their fourth album Mismo Sitio, Distinto Lugar. <a href="https://www.last.fm/music/Vetusta+Morla">Read more on Last.fm</a>',
  'listeners': 165033,
  'playcount': '9816418',
  'similares': 'Izal, Supersubmarina, Love of Lesbian, Viva Suecia, Lori Meyers'},
 {'artista': 'Leiva',
  'biografia': 'José Miguel Conejo Torres (Madrid, 30 de abril de 1980), más conocido como Leiva, es un músico, cantautor español y multiinstrumentista de rock. En 2001, formó junto a Rubén Pozo la banda de rock en español Pereza, con la que grabó seis discos hasta su separación en 2011. Tras la disolución del grupo, inició una carrera en solitario en la que lleva cuatro discos grabados. <a href="https://www.last.fm/music/Leiva">Read more on Last.fm</a>',
  'listeners': 90371,
  'playcount': '2526073',
  'similares': 'Pereza, Arde Bogotá, Sidecars, Vetusta Morla, Fito Y Fitipaldis'},
 {'artista': 'Bad Bunny',
  'biografia': 'Benito Antonio Martínez Ocasio (born March 10, 1994), known professionally as Bad Bunny, is a Puerto Rican rapper and singer. He is recognized as a leading figure in Latin trap and has played a significant role in popularizing Spanish-language rap in global mainstream music. Bad Bunny became the first non-English-language artist to be Spotify\'s most-streamed artist of the year, achieving this distinction in three consecutive years from 2020 to 2022. His 2022 album "Un Verano Sin Ti" holds the record as the most-streamed album on Spotify. <a href="https://www.last.fm/music/Bad+Bunny">Read more on Last.fm</a>',
  'listeners': 2580821,
  'playcount': '406701900',
  'similares': 'JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Vegabajeño'},
 {'artista': 'Enrique Bunbury',
  'biografia': 'Enrique Ortiz de Landázuri Izarduy, better known as Enrique Bunbury, was born August 11, 1967 in Zaragoza, Spain. He got involved in music in the early 1980s, making his debut in a high school band called Apocalipsis, and later played along with Proceso Entrópico. In 1984 Bunbury joined a group called Zumo de Vidrio, debuting as a lead vocalist. After adopting the nickname of Bunbury, taken from an Oscar Wilde novel, the musician teamed up with Héroes del Silencio, becoming a major number in the Spanish rock scene. <a href="https://www.last.fm/music/Enrique+Bunbury">Read more on Last.fm</a>',
  'listeners': 149785,
  'playcount': '4886184',
  'similares': 'Héroes del Silencio, Jaguares, Fobia, Elefante, Caifanes'},
 {'artista': 'Marea',
  'biografia': 'Marea is an Spanish rock \'n\' roll band formed in Berriozar, Navarra in 1998. \nThe members of the band are Kutxi Romero as vocalist, Alen Ayerdi as drummer, César Ramallo on rhytmical guitar, David Díaz (Kolibri) as leading guitar and Eduardo Beaumont (Piñas) as bassist and vocalist.\nMarea has recorded five albums since its formation: La Patera (1999), Revolcón (2000), Besos De Perro (2002), 28000 Puñaladas (2004) and Las Aceras Están Llenas De Piojos (2007). <a href="https://www.last.fm/music/Marea">Read more on Last.fm</a>',
  'listeners': 123625,
  'playcount': '5123402',
  'similares': 'La Fuga, Extremoduro, Platero y tú, Fito Y Fitipaldis, Barricada'},
 {'artista': 'Joaquín Sabina',
  'biografia': 'Joaquín Ramón Martínez Sabina (Úbeda, Jaén, Spain, 12 February 1949), known artistically as Joaquín Sabina, is a singer - songwriter, and poet. He has released fourteen studio albums, two live albums, and three compilation albums. He has collaborated and composed songs for Ana Belén and Miguel Ríos amongst others.\n\nJoaquín Sabina, is the second son of Adela Sabina del Campo and Jerónimo Martinez Gallego, which was a policeman. He attended <a href="https://www.last.fm/music/+noredirect/Joaqu%C3%ADn+Sabina">Read more on Last.fm</a>',
  'listeners': 237562,
  'playcount': '7708267',
  'similares': 'Joan Manuel Serrat, Luis Eduardo Aute, Ismael Serrano, Miguel Ríos, Café Quijano'},
 {'artista': 'Rosalía',
  'biografia': 'Rosalia Vila Tobella, known mononymously as ROSALÍA is a Spanish singer and songwriter. Born and raised in the outskirts of Barcelona, she has been described as an "untypical pop star" due to her genre-bending musical styles. After being enthralled by Spanish folk music at age 13, she studied musicology at Catalonia College of Music while also performing at musical bars and weddings. She completed her studies with honors by virtue of her collaborative cover album with Raül Refree, Los Ángeles and the baccalaureate project El Mal Querer. <a href="https://www.last.fm/music/ROSAL%C3%8DA">Read more on Last.fm</a>',
  'listeners': 1867349,
  'playcount': '203697085',
  'similares': 'Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO'},
 {'artista': 'Queen',
  'biografia': 'Queen are a British rock band formed in London in 1970 by Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), and Roger Taylor (drums, vocals), later joined by John Deacon (bass). Their early music was influenced by progressive rock, hard rock, and heavy metal, but the band gradually incorporated more mainstream styles, including arena rock and pop rock.\n\nBefore Queen, May and Taylor played together in the band Smile. Mercury, a fan of Smile <a href="https://www.last.fm/music/Queen">Read more on Last.fm</a>',
  'listeners': 7228254,
  'playcount': '426233867',
  'similares': 'Freddie Mercury, Roger Taylor, Brian May, Freddie Mercury & Montserrat Caballé, Queen + Paul Rodgers'},
 {'artista': 'The Lumineers',
  'biografia': 'The Lumineers is an American folk rock band based in Denver, Colorado formed by Wesley Schultz (lead vocals, guitar) and Jeremiah Fraites (drums, percussion). Schultz and Fraites began writing and performing together in Ramsey, New Jersey in 2005. Cellist and vocalist Neyla Pekarek joined the band in 2010, and was a member until 2018.\n\nThe band\'s debut self-titled album was released on April 3, 2012. The album\'s first single, "Ho Hey" reached #3 on the Billboard Hot 100 and #1 on the Billboard Alternative Songs chart. <a href="https://www.last.fm/music/The+Lumineers">Read more on Last.fm</a>',
  'listeners': 2581910,
  'playcount': '92131692',
  'similares': 'Caamp, The Head and the Heart, Vance Joy, Mt. Joy, Mumford & Sons'},
 {'artista': 'Foo Fighters',
  'biografia': 'Foo Fighters are an American rock band formed in Seattle in 1994. Initially founded as a one-man project by former Nirvana drummer Dave Grohl, the band has included Grohl (vocals and guitar), Nate Mendel (bass), Pat Smear (guitar), Chris Shiflett (guitar), Rami Jaffee (keyboards), and Ilan Rubin (drums). Former members have included Franz Stahl (guitar), William Goldsmith (drums), Taylor Hawkins (drums), and Josh Freese (drums).\n\nGrohl created the project to release solo material following the disbandment of Nirvana in 1994. <a href="https://www.last.fm/music/Foo+Fighters">Read more on Last.fm</a>',
  'listeners': 6374182,
  'playcount': '364006454',
  'similares': 'Pearl Jam, Taylor Hawkins & The Coattail Riders, Audioslave, Them Crooked Vultures, Red Hot Chili Peppers'},
 {'artista': 'Muse',
  'biografia': 'Muse is an English rock band from Teignmouth, Devon, formed in 1994. The band consists of Matt Bellamy (lead vocals, guitar, keyboards), Chris Wolstenholme (bass guitar, backing vocals), and Dominic Howard (drums, percussion).\n\nMuse released their debut album, "Showbiz," in 1999, which featured Bellamy\'s falsetto and a melancholic alternative rock style. Their second album, "Origin of Symmetry" (2001), incorporated wider instrumentation and classical influences and contributed to their reputation for energetic live performances. <a href="https://www.last.fm/music/Muse">Read more on Last.fm</a>',
  'listeners': 6396593,
  'playcount': '571348879',
  'similares': 'Royal Blood, Placebo, Nothing But Thieves, Radiohead, Franz Ferdinand'},
 {'artista': 'Metallica',
  'biografia': 'Metallica is an American heavy metal band formed in Los Angeles in 1981 by vocalist and guitarist James Hetfield and drummer Lars Ulrich, and later based primarily in San Francisco. The band is regarded as one of the leading acts in thrash metal, alongside Megadeth, Anthrax, and Slayer. Its core lineup has long consisted of Hetfield, Ulrich, lead guitarist Kirk Hammett, and bassist Robert Trujillo. Former members include Dave Mustaine, who later formed Megadeth, and bassists Ron McGovney, Cliff Burton, and Jason Newsted. <a href="https://www.last.fm/music/Metallica">Read more on Last.fm</a>',
  'listeners': 5185293,
  'playcount': '535774615',
  'similares': 'Megadeth, Slayer, Pantera, Anthrax, Iron Maiden'},
 {'artista': 'Ginebras',
  'biografia': 'Ginebras is a Spanish indie rock musical band formed in 2018. Its members are four women: Magüi Berto (voice and guitar), Sandra Sabater (lead guitar), Raquel López (bass) and Juls Acosta (drums).\n\nThe group was formed in 2018 at the initiative of Magüi Berto and Sandra Sabater, who studied audiovisual communication at the Complutense University of Madrid and played the electric guitar.\nThrough an advertisement on Tinder, where they were looking for girls to play bass and guitar. <a href="https://www.last.fm/music/Ginebras">Read more on Last.fm</a>',
  'listeners': 22168,
  'playcount': '690618',
  'similares': 'Cariño, Karavana, Shego, Niña Polaca, Carolina Durante'},
 {'artista': 'IZAL',
  'biografia': 'In 2010, with more than 10 years of experience behind them, five musicians came together to form IZAL. A band made up of Mikel Izal (vocals, composer, guitar, ukulele), Emanuel Pérez “Gato” (bass), Alejandro Jordá (drums and percussion), Alberto Pérez (guitar, Lap Steel) and Iván Mella (piano, keyboards, synthesizers ). Coming from different geographical locations, Madrid became their "base" of operations, which is why the name "Madrid band" has been highly honored since its inception, despite not being originally from the capital. <a href="https://www.last.fm/music/Izal">Read more on Last.fm</a>',
  'listeners': 66750,
  'playcount': '3071775',
  'similares': 'Viva Suecia, Vetusta Morla, Supersubmarina, Arde Bogotá, Lori Meyers'},
 {'artista': 'Kaiser Chiefs',

In [103]:
#Crear DataFrame
df_lastfm = pd.DataFrame(resultados)
df_lastfm.head() #con esto veo 5

,artista,biografia,listeners,playcount,similares
0,La Fuga,Spanish rock band La Fuga were born in July of...,82570,2800704,"Marea, Platero y tú, Rosendo, Los De Marras, F..."
1,Héroes del Silencio,Héroes del Silencio (sometimes referred to as ...,202353,6110116,"Enrique Bunbury, Caifanes, Jaguares, Fobia, Ra..."
2,Billie Eilish,Billie Eilish Pirate Baird O'Connell (born Dec...,4230582,836351191,"FINNEAS, Olivia Rodrigo, Melanie Martinez, Lan..."
3,Love of Lesbian,Love of Lesbian is a Spanish indie pop/indie r...,176513,11440267,"Lori Meyers, Viva Suecia, Izal, Vetusta Morla,..."
4,Estopa,Estopa is a pop/flamenco duo founded in 1999 b...,309127,8958630,"Melendi, El Canto del Loco, Extremoduro, Perez..."

In [104]:
df_lastfm #con esto sale toda la tabla

,artista,biografia,listeners,playcount,similares
0,La Fuga,Spanish rock band La Fuga were born in July of...,82570,2800704,"Marea, Platero y tú, Rosendo, Los De Marras, F..."
1,Héroes del Silencio,Héroes del Silencio (sometimes referred to as ...,202353,6110116,"Enrique Bunbury, Caifanes, Jaguares, Fobia, Ra..."
2,Billie Eilish,Billie Eilish Pirate Baird O'Connell (born Dec...,4230582,836351191,"FINNEAS, Olivia Rodrigo, Melanie Martinez, Lan..."
3,Love of Lesbian,Love of Lesbian is a Spanish indie pop/indie r...,176513,11440267,"Lori Meyers, Viva Suecia, Izal, Vetusta Morla,..."
4,Estopa,Estopa is a pop/flamenco duo founded in 1999 b...,309127,8958630,"Melendi, El Canto del Loco, Extremoduro, Perez..."
5,Mägo de Oz,"Mägo de Oz (Spanish for Wizard of Oz, with a m...",298682,13967733,"Warcry, Saratoga, Saurom, Tierra Santa, Rata B..."
6,Mr. Kilombo,Mr.Kilombo es una banda mestiza nacida en Madr...,18654,219292,"Pedro Pastor, TéCanela, El Niño de La Hipoteca..."
7,Rozalén,María de los Ángeles Rozalén Ortuño known as R...,50813,808513,"Vanesa Martín, Amaral, Despistaos, Valeria Cas..."
8,Taburete,"<a href=""https://www.last.fm/music/taburete"">...",38467,699817,"Maldita Nerea, Siloé, Despistaos, Antonio Oroz..."
9,Extremoduro,Extremoduro is a Spanish rock band from Plasen...,181621,12244527,"Marea, Platero y tú, Fito Y Fitipaldis, La Fug..."
10,La Plazuela,La Plazuela is a band from Granada (Spain) for...,14790,413329,"Califato ¾, Los Delinqüentes, María José Llerg..."
11,Veintiuno,Veintiuno is a Spanish indie rock band from To...,21487,593279,"Siloé, Sidonie, Lori Meyers, Miss Caffeina, Sa..."
12,Ojete Calor,Ojete Calor is a electropop (or 'subnopop' as ...,21998,411650,"Ginebras, Siloé, Rozalén, Rigoberta Bandini, L..."
13,Rata Blanca,Rata Blanca was founded in 1985 by Walter Giar...,199839,3903971,"Mägo de Oz, Ángeles del Infierno, Tierra Santa..."
14,Vetusta Morla,Vetusta Morla is a Spanish indie rock band ori...,165033,9816418,"Izal, Supersubmarina, Love of Lesbian, Viva Su..."
15,Leiva,"José Miguel Conejo Torres (Madrid, 30 de abril...",90371,2526073,"Pereza, Arde Bogotá, Sidecars, Vetusta Morla, ..."
16,Bad Bunny,"Benito Antonio Martínez Ocasio (born March 10,...",2580821,406701900,"JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Vega..."
17,Enrique Bunbury,"Enrique Ortiz de Landázuri Izarduy, better kno...",149785,4886184,"Héroes del Silencio, Jaguares, Fobia, Elefante..."
18,Marea,Marea is an Spanish rock 'n' roll band formed ...,123625,5123402,"La Fuga, Extremoduro, Platero y tú, Fito Y Fit..."
19,Joaquín Sabina,"Joaquín Ramón Martínez Sabina (Úbeda, Jaén, Sp...",237562,7708267,"Joan Manuel Serrat, Luis Eduardo Aute, Ismael ..."
20,Rosalía,"Rosalia Vila Tobella, known mononymously as RO...",1867349,203697085,"Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO"
21,Queen,Queen are a British rock band formed in London...,7228254,426233867,"Freddie Mercury, Roger Taylor, Brian May, Fred..."
22,The Lumineers,The Lumineers is an American folk rock band ba...,2581910,92131692,"Caamp, The Head and the Heart, Vance Joy, Mt. ..."
23,Foo Fighters,Foo Fighters are an American rock band formed ...,6374182,364006454,"Pearl Jam, Taylor Hawkins & The Coattail Rider..."
24,Muse,"Muse is an English rock band from Teignmouth, ...",6396593,571348879,"Royal Blood, Placebo, Nothing But Thieves, Rad..."
25,Metallica,Metallica is an American heavy metal band form...,5185293,535774615,"Megadeth, Slayer, Pantera, Anthrax, Iron Maiden"
26,Ginebras,Ginebras is a Spanish indie rock musical band ...,22168,690618,"Cariño, Karavana, Shego, Niña Polaca, Carolina..."
27,IZAL,"In 2010, with more than 10 years of experience...",66750,3071775,"Viva Suecia, Vetusta Morla, Supersubmarina, Ar..."
28,Kaiser Chiefs,Kaiser Chiefs is a post-britpop band which for...,2882767,70449839,"Kasabian, Razorlight, Hard-Fi, The Fratellis, ..."
29,Residente,Residente (born René Pérez Joglar; February 23...,185421,2689421,"Calle 13, Ana Tijoux, Los Rivera Destino, Vico..."

In [105]:
#para verlos en orden de más popular a menos 
df_lastfm.sort_values(by="listeners", ascending=False)

,artista,biografia,listeners,playcount,similares
21,Queen,Queen are a British rock band formed in London...,7228254,426233867,"Freddie Mercury, Roger Taylor, Brian May, Fred..."
24,Muse,"Muse is an English rock band from Teignmouth, ...",6396593,571348879,"Royal Blood, Placebo, Nothing But Thieves, Rad..."
23,Foo Fighters,Foo Fighters are an American rock band formed ...,6374182,364006454,"Pearl Jam, Taylor Hawkins & The Coattail Rider..."
25,Metallica,Metallica is an American heavy metal band form...,5185293,535774615,"Megadeth, Slayer, Pantera, Anthrax, Iron Maiden"
2,Billie Eilish,Billie Eilish Pirate Baird O'Connell (born Dec...,4230582,836351191,"FINNEAS, Olivia Rodrigo, Melanie Martinez, Lan..."
28,Kaiser Chiefs,Kaiser Chiefs is a post-britpop band which for...,2882767,70449839,"Kasabian, Razorlight, Hard-Fi, The Fratellis, ..."
22,The Lumineers,The Lumineers is an American folk rock band ba...,2581910,92131692,"Caamp, The Head and the Heart, Vance Joy, Mt. ..."
16,Bad Bunny,"Benito Antonio Martínez Ocasio (born March 10,...",2580821,406701900,"JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Vega..."
20,Rosalía,"Rosalia Vila Tobella, known mononymously as RO...",1867349,203697085,"Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO"
4,Estopa,Estopa is a pop/flamenco duo founded in 1999 b...,309127,8958630,"Melendi, El Canto del Loco, Extremoduro, Perez..."
5,Mägo de Oz,"Mägo de Oz (Spanish for Wizard of Oz, with a m...",298682,13967733,"Warcry, Saratoga, Saurom, Tierra Santa, Rata B..."
19,Joaquín Sabina,"Joaquín Ramón Martínez Sabina (Úbeda, Jaén, Sp...",237562,7708267,"Joan Manuel Serrat, Luis Eduardo Aute, Ismael ..."
1,Héroes del Silencio,Héroes del Silencio (sometimes referred to as ...,202353,6110116,"Enrique Bunbury, Caifanes, Jaguares, Fobia, Ra..."
13,Rata Blanca,Rata Blanca was founded in 1985 by Walter Giar...,199839,3903971,"Mägo de Oz, Ángeles del Infierno, Tierra Santa..."
29,Residente,Residente (born René Pérez Joglar; February 23...,185421,2689421,"Calle 13, Ana Tijoux, Los Rivera Destino, Vico..."
9,Extremoduro,Extremoduro is a Spanish rock band from Plasen...,181621,12244527,"Marea, Platero y tú, Fito Y Fitipaldis, La Fug..."
3,Love of Lesbian,Love of Lesbian is a Spanish indie pop/indie r...,176513,11440267,"Lori Meyers, Viva Suecia, Izal, Vetusta Morla,..."
14,Vetusta Morla,Vetusta Morla is a Spanish indie rock band ori...,165033,9816418,"Izal, Supersubmarina, Love of Lesbian, Viva Su..."
17,Enrique Bunbury,"Enrique Ortiz de Landázuri Izarduy, better kno...",149785,4886184,"Héroes del Silencio, Jaguares, Fobia, Elefante..."
18,Marea,Marea is an Spanish rock 'n' roll band formed ...,123625,5123402,"La Fuga, Extremoduro, Platero y tú, Fito Y Fit..."
15,Leiva,"José Miguel Conejo Torres (Madrid, 30 de abril...",90371,2526073,"Pereza, Arde Bogotá, Sidecars, Vetusta Morla, ..."
0,La Fuga,Spanish rock band La Fuga were born in July of...,82570,2800704,"Marea, Platero y tú, Rosendo, Los De Marras, F..."
27,IZAL,"In 2010, with more than 10 years of experience...",66750,3071775,"Viva Suecia, Vetusta Morla, Supersubmarina, Ar..."
7,Rozalén,María de los Ángeles Rozalén Ortuño known as R...,50813,808513,"Vanesa Martín, Amaral, Despistaos, Valeria Cas..."
8,Taburete,"<a href=""https://www.last.fm/music/taburete"">...",38467,699817,"Maldita Nerea, Siloé, Despistaos, Antonio Oroz..."
26,Ginebras,Ginebras is a Spanish indie rock musical band ...,22168,690618,"Cariño, Karavana, Shego, Niña Polaca, Carolina..."
12,Ojete Calor,Ojete Calor is a electropop (or 'subnopop' as ...,21998,411650,"Ginebras, Siloé, Rozalén, Rigoberta Bandini, L..."
11,Veintiuno,Veintiuno is a Spanish indie rock band from To...,21487,593279,"Siloé, Sidonie, Lori Meyers, Miss Caffeina, Sa..."
6,Mr. Kilombo,Mr.Kilombo es una banda mestiza nacida en Madr...,18654,219292,"Pedro Pastor, TéCanela, El Niño de La Hipoteca..."
10,La Plazuela,La Plazuela is a band from Granada (Spain) for...,14790,413329,"Califato ¾, Los Delinqüentes, María José Llerg..."

In [ ]:
#para unir con Dezzer?? cual es mi df_deezer
df_final = df_deezer.merge(df_lastfm, on="artista", how="left")
df_final.head()